services:
  - type: web
    name: flask-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: REDIS_URL
        fromService:
          name: your-redis-service-name
          type: redis
          property: connectionString

  - type: worker
    name: celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A worker worker --loglevel=info"
    envVars:
      - key: REDIS_URL
        fromService:
          name: your-redis-service-name
          type: redis
          property: connectionString
