services:
  - type: web
    name: ai-yt-flask
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: REDIS_URL
        value: redis://red-d1lq916mcj7s73ar5ejg:6379

  - type: worker
    name: ai-yt-worker
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A worker worker --loglevel=info"
    envVars:
      - key: REDIS_URL
        value: redis://red-d1lq916mcj7s73ar5ejg:6379
